### ISSUE TITLE
Any plans to include c_str! into std:: ?

### ISSUE THREAD

**Issue by Dushistov** [mzabaluev/rust-c-str#1]
Add dependency to external crate just for `c_str!` macro is overhead IMHO,
so reimplement it time to time.

Any plans to create rfc and include `c_str!` into stdlib?

**Comment by mzabaluev** [comment]
No, but I could think of spinning it off as a macro-only crate.

**Comment by mzabaluev** [comment]
This crate is now named `c_str_macro` and provides only the macro. It has been published under the stable 1.0.0 version number, so dependencies can be versioned more dependably and depending crates can be legally stabilized in turn.

With that, I don't see a need to contribute the macro to the standard library as the micro-crate should be good enough.
